#+TITLE:  
#+AUTHOR: VLEAD
#+DATE: [2015-10-27 Tue]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil

* Git
** Proxy Configuration
   - If your network has any proxy settings to access internet please ensure that they are
     set to =http_proxy= and =https_proxy= variables
 #+BEGIN_SRC shell :tangle configure.sh :eval no
 #!/bin/bash
http_proxy=yourproxy
httsp_proxy=yourproxy
#+END_SRC
** Updating system
   - Before installing =git= package please update =apt= repository from where
     =git= will be installed.
     and check whether updating =apt= repository is successfully done or not if
     not through an error.
     #+BEGIN_SRC shell :tangle install_git.sh :eval no
echo "######### Updating System #########"
sudo apt-get -y update
if [ $? -eq 0 ]
then
    echo "########### Successfully updated ###########"
else
    echo "########### Erro in updating system ###########"
    exit
fi
#+END_SRC

** Installing Git
   - Once updating system is done successfully install =git= version control
     using =apt= command and check whether successfully installed or not.
   #+BEGIN_SRC shell :tangle install_git.sh :eval no
echo "######### Installing Git #########"
sudo apt-get -y install git

if [ $? -eq 0 ]
then
    echo "########### Git is installed successfully ##########"
else
    echo "########### Erro in installing Git ###########"
    exit 1
fi
#+END_SRC

** Git configuration
   - To start with =git= version control please provide your
     =username= and =email= of your =github= account so that it will tack all
     the changes that you have made to project.
 #+BEGIN_SRC shell :tangle configure.sh :eval no
git_username=username
git_email=email
 #+END_SRC
#+BEGIN_SRC shell :tangle install_git.sh :eval no
git config --global user.name $git_username
git config --global user.email $git_email

#+END_SRC
   
* Emacs
** Install dependencies
   - Before installing =emacs24.5.10= version we need to install all required
     dependency packages. They are =build-dep= and =checkinstall=.
#+BEGIN_SRC shell :tangle install_emacs.sh :eval no
#!/bin/bash
sudo apt-get -y build-dep emacs24
if [ $? -eq 0 ]
then
    echo "######### Dependency build-dep installed ###########"
else
    echo "######## Erro in installing build-dep dependency #####"
    exit 1
fi
#+END_SRC
#+BEGIN_SRC shell :tangle install_emacs.sh :eval no
sudo apt-get -y install pylint
if [ $? -eq 0 ]
then
    echo "######### Dependency pylint is installed ###########"
else
    echo "######## Erro in installing pylint  dependency #####"
    exit 1
fi
#+END_SRC

#+BEGIN_SRC shell :tangle install_emacs.sh :eval no
sudo apt-get -y install python-virtualenv
if [ $? -eq 0 ]
then
    echo "######### Dependencies python-virtualenv is installed ###########"
else
    echo "######## Erro in installing python-virtualenv ########"
    exit 1
fi
#+END_SRC
** Downloading =emacs24.5.10.tar.gz= file
   - Before we go ahead with installing emacs please download the emacs source
     file using =wget= command under =~/src= directory.
#+BEGIN_SRC shell :tangle install_emacs.sh :eval no
mkdir -p ~/src
cd ~/src
wget http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz
if [ $? -eq 0 ]
then
    echo "######### emacs-24.5.tar.gz is downloaded ###########"
else
    echo "Error in downlaoding emacs-24.5.tar.gz file"
    exit 1
fi
#+END_SRC
** Installing emacs-24.5.10
   - To install =emacs-24.5.10= source package, untar the downloaded file and run =make=,
     =checkinstall= commands. 
#+BEGIN_SRC shell :tangle install_emacs.sh :eval no
tar xf emacs-24.5.tar.gz
cd emacs-24.5
./configure
make
sudo checkinstall
if [ $? -eq 0 ]
then
    echo "######### Successfully installed checkinstall ###########"
else
    echo "######## Error in running checkinstall ############"
    exit 1
fi

#+END_SRC
* Installation scripts
  - Following code will invoke both the =git= and =emacs= installation scripts.
#+BEGIN_SRC shell :tangle all.sh :eval no
#!/bin/bash
chmod +x install_git.sh
chmod +x install_emacs.sh
./install_git.sh
./install_emacs.sh
#+END_SRC
    
