#+TITLE:  Steps to install git, emacs and configure emacs for integrated development environment
#+AUTHOR: VLEAD
#+DATE: [2015-10-27 Tue]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+options: ^:nil

(*Pre requisites :* The following steps will work on /Ubuntu14.04 x86_64/ OS.

  1. Download the /emacs-as-ide.tar/ file (Ignore if alraady downloaded)
     #+begin_example
     wget http://files.vlabs.ac.in/downloads/emacs-as-ide.tar
     #+end_example

  2. Untar the /emacs-as-ide.tar/ file
     #+begin_example
     tar xvf emacs-as-ide.tar
     #+end_example

  3. Change directory to =src= folder
     #+begin_example
     cd code/src/
     #+end_example

  4. To configure proxy open file using
     #+begin_example
     vim configure.sh
     #+end_example

  5. If you are using proxy settings please relace =yourproxy= with appropriate
     values, if you are not using comment below lines using =#=
     #+begin_example
     http_proxy=yourproxy
     https_proxy=yourproxy
     at IIIT, the proxy is http://proxy.iiit.ac.in:8080
     #+end_example

  6. To configure git please replace =username= and =email= with appropriate
     values
     #+begin_example
     git_username=gitusername
     git_email=gitemail
     #+end_example

  7. Run the script
     #+begin_example
     chmod +x all.sh
     ./all.sh
     #+end_example

     + While script is running it will ask for various confirmation please give a
       confirmation as below
     + Postfix Configuration - =Ok=
     + Out of list please select =No Configuration=
     + Should I create a default set of package docs? Say =n= and press enter
     + Press enter
     + Press enter
     + You probably don't want them to be included in the package. Do you want
       me to list them?  Say =n= and press enter
     + Should I exclude them from the package? Say =y= and press enter 
     + Copying files to the temparory directory ( 5-10 mins)
     + Once installation is done

  8. Open emacs using command
     #+begin_example
     emacs &
     #+end_example

  9. List all the available packages on emacs and click on package to install.
       M-x in which M = Alt key
     #+begin_example
     M-x list-packages
     #+end_example
     
     From available packages install the following
     + column-marker
     + yasnippet
     + quack
     + ox-reveal
     + js2-mode
     + auto-complete
     + jedi
     + flycheck
     + python-mode
     + pylint
     + To install jedi:install-server press M-x and type jedi:install-server.
     
  10. Close the emacs and reopen to check applied changes

* Debain9 installation

- Download the iso
#+BEGIN_EXAMPLE
wget https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-9.1.0-amd64-DVD-1.iso
#+END_EXAMPLE
- Make USB drive as bootable using below command
#+BEGIN_EXAMPLE
sudo dd if=<.iso file path> of=<usb path> status=progress
#+END_EXAMPLE
- Insert pendrive and change the boot sequece to =USB= in bios settings
- Install the OS
- Once OS installation is completed add below lines to =/et/apt/souces.list=
  file
#+BEGIN_EXAMPLE
deb http://ftp.us.debian.org/debian/ stretch main contrib non-free
deb http://security.debian.org/ stretch/updates main contrib non-free 
deb http://httpredir.debian.org/debian/ jessie main contrib non-free

#+END_EXAMPLE
- Update the system
#+BEGIN_EXAMPLE
su -
apt-get update -y
#+END_EXAMPLE
- Install emacs
#+BEGIN_EXAMPLE
apt-get install emacs
#+END_EXAMPLE
- Copy =dot-emacs.el= file to =~/.emacs=
#+BEGIN_EXAMPLE
cp vlead-onboarding/build/code/src/do-emacs.el ~/.emacs
#+END_EXAMPLE
- Install packages on emacs

  + List all the available packages on emacs and click on package to
    install. 
#+BEGIN_EXAMPLE
M-x list-packages
#+END_EXAMPLE
  + From available packages install the following
#+BEGIN_EXAMPLE
    column-marker
    yasnippet
    quack
    ox-reveal
    js2-mode
    auto-complete
    jedi
    flycheck
    python-mode
    pylint

#+END_EXAMPLE
  + Install jedi server
#+BEGIN_EXAMPLE
M-x jedi:install-server
#+END_EXAMPLE

  + Close the emacs and reopen to check applied changes

- Install =vagrant= and =virtualbox=
#+BEGIN_EXAMPLE
apt-get install virtualbox
apt-get install vagrant
#+END_EXAMPLE

- Install the dkms package to ensure that the VirtualBox host kernel modules
  (vboxdrv, vboxnetflt and vboxnetadp) are properly updated if the Linux kernel
  version changes during the next apt-get upgrade.
#+BEGIN_EXAMPLE
apt-get install virtualbox-dkms
#+END_EXAMPLE
- Add =ubuntu-dev-env= to vagrant
#+BEGIN_EXAMPLE
vagrant box add ubuntu-dev-env http://community.vlabs.ac.in/downloads/ubuntu-dev-env.box
#+END_EXAMPLE
- Boot up the vagrant machine
#+BEGIN_EXAMPLE
mkdir ubuntu-dev-env
cd ubuntu-dev-env
vagrant init ubuntu-dev-env
vagrant up
#+END_EXAMPLE
- ssh into the machine
#+BEGIN_EXAMPLE
vagrant ssh
#+END_EXAMPLE
